# 知识平台轻量版-演示环境
server {
    
    listen 80;
    server_name _;
    client_max_body_size 5120m; 
    location / {
            # 允许所有来源访问（* 通配符）
            add_header 'Access-Control-Allow-Origin' '*' always;
            # 允许的 HTTP 方法
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS, HEAD' always;
            # 允许的请求头（可按需扩展）
            add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With, Accept, Origin' always;
            proxy_send_timeout 3600;
            proxy_read_timeout 3600; 
            proxy_connect_timeout 3600; 
            proxy_pass http://127.0.0.1:11088/;
    }
    location /biz/ {
            # 业务系统前端
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:11087/;
    }
    location /biz/ribbon.xml {
        # 设置返回内容类型为 XML
        default_type application/xml;
        # 禁用日志（可选：避免刷日志）
        access_log off;
        # 开启压缩（可选）
        gzip_static on;

        # 使用 return 返回原始 XML 内容
        return 200 '<customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui" onLoad="ribbon.OnAddinLoad">
		<ribbon startFromScratch="false">
		    <tabs>
			<tab id="AICompliance" label="中建投AI">
			    <group id="btnGroup" label="btnGroup">
                    <button id="agentView" label="问知问数" onAction="ribbon.OnAction" getEnabled="true"  getImage="ribbon.GetImage" getVisible="true" size="large"/>
                    <button id="portrayal" label="客商准入" onAction="ribbon.OnAction" getEnabled="true"  getImage="ribbon.GetImage" visible="true" size="large"/>
                    <button id="contractDrafting" label="合同起草" onAction="ribbon.OnAction" getEnabled="true"  getImage="ribbon.GetImage" getVisible="true" size="large"/>
                    <button id="contractReview" label="合同审核" onAction="ribbon.OnAction" getEnabled="true"  getImage="ribbon.GetImage" visible="true" size="large"/>
                    <button id="contrastive" label="文档对比" onAction="ribbon.OnAction" getEnabled="true"  getImage="ribbon.GetImage" getVisible="true" size="large"/>
			    </group>
			</tab>
		    </tabs>
		</ribbon>
		</customUI>';
    }
    location /admin-api/ {
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:11080;
    }
    location /admin-api/langflow/ {
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:7860/;
    }
    location /api/ {
            # flow服务后端
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:7860/api/;
    }
    location /health_check {
            # flow服务后端
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:7860;
    }
     location /admin-api/contrastive/ {
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:28077/;
    }
    location /upload-proxy/ {
            # minio的预览
            proxy_pass http://127.0.0.1:9001/;
    }
    location /kg-light/ {
            # minio的预览
            proxy_pass http://127.0.0.1:9001/kg-light/;
    }
    location /upgrade/ {
        # 升级服务
        alias /data/upgrade/www/;
        index index.html;
        try_files $uri $uri/ =404;
    }
    location /upgrade-api/ {
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_connect_timeout 3600;
            proxy_pass http://127.0.0.1:11086/admin-api/;
    }
    location /jenkins/ {
        # jenkins
        proxy_pass http://127.0.0.1:8080/jenkins/;
    }

}
